language: csharp
solution: GoogleMapsApi.sln
install:
  - nuget restore GoogleMapsApi.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GoogleMapsApi.sln
  - mono ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe ./GoogleMapsApi.Test/bin/Release/GoogleMapsApi.Test.dll
