name: Publish Nuget

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish NuGet
        # You may pin to the exact commit or the version.
        # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: GoogleMapsApi/GoogleMapsApi.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: GoogleMapsApi
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          #VERSION_FILE_PATH: # optional
          #VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
          VERSION_STATIC: 0.81.0
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          #NUGET_SOURCE: # optional, default is https://api.nuget.org
          
